// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeHJlsQzCOvKqgvttAj8Ycq0zJMFybNQ8',
    appId: '1:9006298781:web:f2a295ccd2a74e81408674',
    messagingSenderId: '9006298781',
    projectId: 'batch-1-auth',
    authDomain: 'batch-1-auth.firebaseapp.com',
    storageBucket: 'batch-1-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDHEpTF9sito8XYGG0nWGijxUNN3SwgMs',
    appId: '1:9006298781:android:824a08908e25e1f1408674',
    messagingSenderId: '9006298781',
    projectId: 'batch-1-auth',
    storageBucket: 'batch-1-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKImQWm3CnHukE4g4dSr-AnihdaQ1xBZU',
    appId: '1:9006298781:ios:4ce214460c3b2567408674',
    messagingSenderId: '9006298781',
    projectId: 'batch-1-auth',
    storageBucket: 'batch-1-auth.appspot.com',
    iosBundleId: 'com.example.firebaseAuthBatch1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKImQWm3CnHukE4g4dSr-AnihdaQ1xBZU',
    appId: '1:9006298781:ios:2969551bad7f9257408674',
    messagingSenderId: '9006298781',
    projectId: 'batch-1-auth',
    storageBucket: 'batch-1-auth.appspot.com',
    iosBundleId: 'com.example.firebaseAuthBatch1.RunnerTests',
  );
}
